project: 
  type: website

website: 
  title: "der Blog"
  navbar: 
    right: 
      - href: about.qmd
        text: über mich

  sidebar: 
    style: docked
    contents: 
      - section: "Einträge"
        contents: 
        - href: docs/entries/entry1.qmd
          text: mein erster Eintrag
        - href: docs/entries/entry2.qmd
          text: zweiter Eintrag
  
  page-footer: 
    center: "Copyright 2024, Edna Grewers"
    right: 
      - icon: github
        href: https://github.com
  
format: 
  html: 
    theme: darkly